Models/Calculadora.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace PAGINAS.Models
{
    public class Calculadora
    {
        public int Operador1 { get; set; }
        public int Operador2 { get; set; }

        public String Acccion { get; set; }

        [Display(Name="Output")]
        public int Respuesta { get; set; }

    }
}

Models/Contacto.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PAGINAS.Models
{
    public class Contacto
    {
        [Required(ErrorMessage = "Por favor ingrese Nombre")]
        [Display(Name="Nombre")]
        public String Name { get; set; }

        [Required(ErrorMessage = "Por favor ingrese Apellido")]
        [Display(Name="Apellido")]
        public String LastName { get; set; }

        [Display(Name="Email")]
        public String Email { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name="Telefono")]
        public int Phone { get; set; }

        [Display(Name="Titulo")]
        public String Subject { get; set; }

        [Display(Name="Mensaje")]
        public String Message { get; set; }

        public String Response { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace PAGINAS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Estudiante.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PAGINAS.Models
{
    public class Estudiante
    {
        [Required(ErrorMessage = "Por favor, ingrese el Nombre")]
        [Display(Name="Nombre")]
        public String Name { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese el Apellido")]
        [Display(Name="Apellido")]
        public String LastName { get; set; }
        
        public String Acccion { get; set; }

        public String Response { get; set; }

    }
}

Controllers/CalculadoraController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PAGINAS.Models;

namespace PAGINAS.Controllers
{
    public class CalculadoraController : Controller
    {
        private readonly ILogger<CalculadoraController> _logger;

        public CalculadoraController(ILogger<CalculadoraController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Calcular(Calculadora objCalculadora){
            if("+".Equals(objCalculadora.Acccion)){
                objCalculadora.Respuesta = objCalculadora.Operador1 + objCalculadora.Operador2;
            }
            if("-".Equals(objCalculadora.Acccion)){
                objCalculadora.Respuesta = objCalculadora.Operador1 - objCalculadora.Operador2;
            }            
            return View("index", objCalculadora);
        }

    }
}

Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PAGINAS.Models;

namespace PAGINAS.Controllers
{
    public class ContactoController : Controller
    {

       private readonly ILogger<ContactoController> _logger;

        public ContactoController(ILogger<ContactoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(Contacto objContacto){
            if (ModelState.IsValid)
            {
                objContacto.Response = "Gracias estamos en contacto";
            }
            return View("index", objContacto);
        }

    }
}

Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PAGINAS.Models;

namespace PAGINAS.Controllers
{
    public class EstudianteController : Controller
    {

       private readonly ILogger<EstudianteController> _logger;

        public EstudianteController(ILogger<EstudianteController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(Estudiante objEstudiante){
            if (ModelState.IsValid)
            {
                objEstudiante.Response = "Registro de Base de Datos (*)";
            }
            return View("index", objEstudiante);
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PAGINAS.Models;

namespace PAGINAS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calculadora/Index.cshtml
@model PAGINAS.Models.Calculadora


@{
    ViewData["Title"] = "Calculadora Page";
}

<div class="text-center">
    <h1 class="display-4">Calculadora</h1>
    <form asp-controller="Calculadora" asp-action="Calcular">
            
            <label>Operador1</label>
            <input asp-for="Operador1"/>
            <br/>

            <label>Operador2</label>
            <input asp-for="Operador2"/>
            <br/>

            <label>Operando</label>
            <select asp-for="Acccion">
                <option value="+">Suma</option>
                <option value="-">Resta</option>
                <option value="*">Multiplicacion</option>
                <option value="/">Division</option>
            </select>
            <br/>
            
            <input type="submit" value="Calcular"/>
    </form>
    
    <td>@Html.DisplayNameFor(model => model.Respuesta)</td>
    <td>@Html.DisplayTextFor(model => model.Respuesta)</td>

</div>

Views/Contacto/Index.cshtml
@model PAGINAS.Models.Contacto

@{
    ViewData["Title"] = "Contacto";
}

<div class="row">
    <div class="col-md-4">  
        <h1 class="display-4">Contacto</h1>
        <form asp-controller="Contacto" asp-action="Registrar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>    

            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>               
                   
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
            </div>               

            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
            </div>               

            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
            </div>    

            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <textarea asp-for="Message" class="form-control" /></textarea>
            </div>                

            <div class="form-group">
                 <button type="submit" class="btn btn-default">Registrar</button> 
            </div>                

        </form>
            
        <td>@Html.DisplayTextFor(model => model.Response)</td>    
    
    </div>
</div>

Views/Estudiante/Index.cshtml
@model PAGINAS.Models.Estudiante

@{
    ViewData["Title"] = "Estudiante";
}

<div class="row">
    <div class="col-md-4">  
        <h1 class="display-4">Estudiante</h1>
        <form asp-controller="Estudiante" asp-action="Registrar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>    

            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>    

              <label>Curso</label>
            <select asp-for="Acccion">
                <option >Matematica</option>
                <option >Talleres</option>
                <option >Programacion</option>
                <option >Software</option>
                <option >Investigacion</option>
                <option >Proyectos</option>
                <option >Ecuaciones Diferenciales</option>
                <option >Algoritmos</option>
                <option >Estadística</option>                
            </select>
            <br/>         

            <div class="form-group">
                 <button type="submit" class="btn btn-warning">Registrar</button> 
            </div>                

        </form>
            
        <td>@Html.DisplayTextFor(model => model.Response)</td>    
    
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PAGINAS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">pagina</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Contacto</a>
                        </li>    

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estudiante" asp-action="Index">Estudiante</a>
                        </li>                    

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PAGINAS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>